<?php
/**
 * Created by PhpStorm.
 * User: mac
 * Date: 2019/5/17
 * Time: 下午5:06
 */

namespace app\controllers;


use app\models\Active;
use app\models\Basic;
use app\models\Career;
use app\models\Employe;
use app\models\Job;
use app\models\News;
use app\models\Product;
use MongoDB\Driver\Server;
use Yii;

class ApiController extends WebBaseController
{
    public function init()
    {
        Yii::$app->response->format = 'json';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionNewsList(){
        $page = intval(Yii::$app->request->get('page'));
        $size = intval(Yii::$app->request->get('size', 10));
        $start = ($page - 1) * $size;

        $query = News::find()->andWhere(['status' => 1,'shelf_status'=>1]);


        $result = $query->orderBy(['sort'=>SORT_DESC,'id'=>SORT_DESC])->limit((int)$size)->offset($start)->asArray()->all();
        $count = $query->count('id');

        return [
            "recordsTotal" => $count,
            "recordsFiltered" => $count,
            "data" => $result
        ];
    }

    public function actionNdetail(){
        $id = Yii::$app->request->get('id');
        $data = News::findOne(['id'=>$id,'status'=>1,'shelf_status'=>1]);
        $data['content'] = str_replace('%domain%', Yii::$app->params['qiniu']['domain'],$data['content']);
        return ['code'=>200,'data'=>$data];
    }

    public function actionActiveList(){
        $list = Active::find()->andWhere(['status'=>1,'shelf_status'=>1])->orderBy(['sort'=>SORT_DESC,'id'=>SORT_DESC])->all();
        return ['code'=>200,'data'=>$list];
    }

    public function actionExper(){
        $data = Basic::findOne(['id'=>1]);
        $list = Product::find()->andWhere(['status'=>1,'shelf_status'=>1,'is_experience'=>1])
            ->orderBy(['is_top'=>SORT_DESC,'sort'=>SORT_DESC,'id'=>SORT_DESC])->limit(2)->indexBy('id')
            ->all();
        return ['code'=>200,'data'=>$data,'list'=>$list];
    }

    public function actionProductList(){
        $list = Product::find()->andWhere(['status'=>1,'shelf_status'=>1,'is_experience'=>0])
            ->orderBy(['sort'=>SORT_DESC,'id'=>SORT_DESC])
            ->all();
        return ['code'=>200,'list'=>$list];
    }

    public function actionJobList(){
        $list = Job::find()->andWhere(['status'=>1,'shelf_status'=>1])
            ->orderBy(['sort'=>SORT_DESC,'id'=>SORT_DESC])->all();
        $employe = Employe::find()->andWhere(['status'=>1,'shelf_status'=>1])->orderBy(['sort'=>SORT_DESC,'id'=>SORT_DESC])->one();
        return ['code'=>200,'list'=>$list,'data'=>$employe];
    }

    public function actionEmployList(){
        $list = Employe::find()->andWhere(['status'=>1,'shelf_status'=>1])
            ->orderBy(['sort'=>SORT_DESC,'id'=>SORT_DESC])->all();
        return ['code'=>200,'list'=>$list];
    }

    public function actionDevelop(){
        $data = Career::findOne(['id'=>1]);
        $data['content'] = str_replace('%domain%', Yii::$app->params['qiniu']['domain'],$data['content']);
        return ['code'=>200,'data'=>$data];
    }
}
